In [81]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

In [82]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [101]:
# Convert categorical data to numeric and separate target feature for training data
X_train = train_df.drop(['Unnamed: 0','index','debt_settlement_flag'], axis=1)
y_train = X_train['loan_status']
y_train = LabelEncoder().fit_transform(y_train)

# y_train = X_train[["hardship_flag","debt_settlement_flag"]]
# X_train = X_train.drop('loan_status',axis=1)

X_train = pd.get_dummies(X_train)
X_train.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Verified,loan_status_high_risk,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y
0,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,0.0,39728.0,...,0,0,1,1,0,1,1,0,1,0
1,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,0.0,9585.0,...,0,0,1,1,0,1,1,0,1,0
2,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,0.0,16708.0,...,0,0,1,1,0,1,1,0,1,0
3,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,1.0,8809.0,...,0,0,1,1,0,1,1,0,1,0
4,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,0.0,65420.0,...,0,0,1,1,0,1,1,0,1,0

In [100]:
# Convert categorical data to numeric and separate target feature for testing data
X_test = test_df.drop(['Unnamed: 0','index','debt_settlement_flag'], axis=1)
y_test = X_test['loan_status']
y_test = LabelEncoder().fit_transform(y_test)

# y_test_debtsettle = LabelEncoder().fit_transform(X_test['hardship_flag'])
# y_test_hardship = LabelEncoder().fit_transform(X_test['debt_settlement_flag'])
# X_test = X_test.drop("loan_status",axis=1)

X_test = pd.get_dummies(X_test)
X_test.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Verified,loan_status_high_risk,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y
0,40000.0,0.0819,814.70,140000.0,19.75,0.0,1.0,18.0,0.0,9471.0,...,0,0,1,1,0,1,1,0,1,0
1,6000.0,0.1524,208.70,55000.0,11.52,2.0,0.0,8.0,0.0,1280.0,...,0,0,1,1,0,1,1,0,1,0
2,3600.0,0.1695,128.27,42000.0,6.74,0.0,0.0,6.0,0.0,4757.0,...,0,0,1,1,0,1,1,0,1,0
3,20000.0,0.1524,478.33,100000.0,12.13,0.0,2.0,7.0,0.0,12731.0,...,0,0,1,1,0,1,1,0,1,0
4,3600.0,0.1240,120.27,50000.0,16.08,0.0,3.0,6.0,0.0,10413.0,...,0,0,1,1,0,1,1,0,1,0

In [85]:
# add missing dummy variables to testing set

In [102]:
# Train the Logistic Regression model on the unscaled data and print the model score
clf = LogisticRegression()
clf.fit(X_train,y_train)

print(f"Training Data Score: {round(clf.score(X_train, y_train),2)*100}%")
print(f"Testing Data Score: {round(clf.score(X_test, y_test),2)*100}%")

Training Data Score: 65.0%
Testing Data Score: 52.0%

C:\Users\Doc\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [124]:
# Train a Random Forest Classifier model and print the model score
clf = RandomForestClassifier(random_state=1, n_estimators=1).fit(X_train,y_train)

print(f"Training Data Score: {round(clf.score(X_train, y_train),2)*100}%")
print(f"Testing Data Score: {round(clf.score(X_test, y_test),2)*100}%")

Training Data Score: 99.0%
Testing Data Score: 97.0%

In [119]:
# Scale the data
scale_train = StandardScaler().fit(X_train)
X_train_scaled = scale_train.transform(X_train)
X_train_scaled

scale_test = StandardScaler().fit(X_test)
X_test_scaled = scale_test.transform(X_test)
X_test_scaled

array([[ 2.27394814, -1.13282185,  1.06131775, ..., -0.35907043,
         0.1323959 , -0.1323959 ],
       [-1.08518753,  0.08480141, -1.00546758, ..., -0.35907043,
         0.1323959 , -0.1323959 ],
       [-1.32230299,  0.38013981, -1.27977706, ..., -0.35907043,
         0.1323959 , -0.1323959 ],
       ...,
       [-0.6899951 ,  1.43368618, -0.39614106, ..., -0.35907043,
         0.1323959 , -0.1323959 ],
       [-0.88759132,  0.66856972, -1.0151535 , ..., -0.35907043,
         0.1323959 , -0.1323959 ],
       [ 1.28596706,  1.00190488,  2.11394584, ..., -0.35907043,
         0.1323959 , -0.1323959 ]])

In [120]:
# Train the Logistic Regression model on the scaled data and print the model score
clf.fit(X_train_scaled,y_train)

print(f"Training Data Score: {round(clf.score(X_train_scaled, y_train_debtsettle),2)*100}%")
print(f"Testing Data Score: {round(clf.score(X_test_scaled, y_test_debtsettle),2)*100}%")

Training Data Score: 49.0%
Testing Data Score: 50.0%

In [123]:
# Train a Random Forest Classifier model on the scaled data and print the model score
clf = RandomForestClassifier(random_state=1, n_estimators=1).fit(X_train_scaled,y_train)

print(f"Training Data Score: {round(clf.score(X_train_scaled, y_train),2)*100}%")
print(f"Testing Data Score: {round(clf.score(X_test_scaled, y_test),2)*100}%")

Training Data Score: 99.0%
Testing Data Score: 97.0%